build.gradle, src/main/resources/application.yml
- 실행 프로필 `local`(로컬), `dev`(개발), `prd`(운영)으로 분리
- `dev`, `prd` 프로필의 경우 로그 레벨과 ddl 설정을 제외하고 거의 동일 (현재 서버, db 1개 밖에 없기 때문)
- `dev`, `prd` 프로필로 실행한 경우에는 parameter store로부터 db 설정 정보를 받아오지만, `local` 프로필로 실행한 경우에는 현재 실행 환경의 환경 변수 값 받아옴
```gradle
spring:
profiles:
default: local
datasource:
url: ${DATABASE_URL}
username: ${DATABASE_ID}
password: ${DATABASE_PASSWORD}
driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
config:
activate:
on-profile: local
jpa:
hibernate:
ddl-auto: update
properties:
hibernate:
highlight_sql: true
show_sql: true
format_sql: true
default_batch_fetch_size: 100
database: mysql
data:
web:
pageable:
one-indexed-parameters: true
logging:
level:
root: info
org.hibernate.sql: info
org.hibernate.type.descriptor.sql: trace
com.project.foradhd: debug
---
spring:
config: …
```
=> AWS Parameter Store DB 관련 설정

build.gradle, src/main/java/com/project/foradhd/domain/auth/business/service/AuthService.java, src/main/java/com/project/foradhd/domain/auth/business/service/JwtService.java, src/main/java/com/project/foradhd/domain/auth/business/service/impl/JwtServiceImpl.java, src/main/java/com/project/foradhd/domain/auth/business/service/impl/UserSignUpTokenServiceImpl.java, src/main/java/com/project/foradhd/domain/auth/handler/JwtLogoutSuccessHandler.java, src/main/java/com/project/foradhd/domain/auth/handler/LoginAuthenticationSuccessHandler.java, src/main/java/com/project/foradhd/domain/auth/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/project/foradhd/global/config/RedisConfig.java, src/main/java/com/project/foradhd/global/service/RedisService.java, src/main/resources/application.yml, src/test/java/com/project/foradhd/ForadhdApplicationTests.java, src/test/java/com/project/foradhd/domain/auth/business/service/AuthServiceTest.java, src/test/java/com/project/foradhd/global/service/RedisServiceTest.java, src/test/java/com/project/foradhd/tags/IntegrationTag.java
- Redis 적용 및 레디스 사용 위한 `RedisService` 구현
- 통합 테스트인 `RedisServiceTest` 작성
- 기존 RT(Refresh Token) 관련 로직에 Redis 적용
- 구현하면서 참고한 [블로그 글](https://green-bin.tistory.com/69)입니다.
- 통합 테스트인 `RedisServiceTest`는 실제 6379 포트에서 Redis가 실행되고 있는 상태여야 테스트에 성공합니다 → 통합 테스트 시에만 `RedisServiceTest` 테스트가 실행되도록 `@IntegrationTag` 커스텀 어노테이션을 정의하고 `RedisServiceTest`에 선언(자세한 내용은 [JUnit5의 @Tag](https://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering) 참고)
```java
@Tag("integration")
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface IntegrationTag {
}
//...
@IntegrationTag //추가
@DisplayName("Redis 서비스 통합 테스트")
@ExtendWith(SpringExtension.class)
@Import({RedisProperties.class, RedisConfig.class, RedisService.class})
class RedisServiceTest { …
```
=> Redis 적용 및 테스트 작성

build.gradle, src/main/java/com/project/foradhd/global/config/AwsS3Config.java, src/main/java/com/project/foradhd/global/exception/ErrorCode.java, src/main/java/com/project/foradhd/global/exception/handler/GlobalExceptionHandler.java, src/main/java/com/project/foradhd/global/image/web/controller/ImageUploadController.java, src/main/java/com/project/foradhd/global/image/web/dto/request/ImageDeleteRequest.java, src/main/java/com/project/foradhd/global/image/web/dto/request/ImageUploadRequest.java, src/main/java/com/project/foradhd/global/image/web/dto/response/ImageUploadResponse.java, src/main/java/com/project/foradhd/global/image/web/enums/ImagePathPrefix.java, src/main/java/com/project/foradhd/global/service/AwsS3Service.java, src/main/java/com/project/foradhd/global/util/ImageUtil.java, src/main/resources/application.yml
- 프로젝트 전반에서 사용할 이미지 업로드 및 삭제 api 구현하였습니다.
```
spring:
servlet:
multipart:
max-file-size: 5MB #하나의 파일 용량 제한
max-request-size: 10MB #하나의 요청 내 전체 파일 용량 제한
resolve-lazily: true #실제 파일에 접근하는 시점에 파일 용량 체크 (스프링 MVC에서 예외 throw)
```
- `resolve-lazily: true`는 파일 용량이 제한을 넘는 경우 발생하는 `MaxUploadSizeExceededException` 예외를 `GlobalExceptionHandler`에서 처리하기 위한 설정입니다. [참고](https://www.inflearn.com/questions/810872/%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C-%ED%81%AC%EA%B8%B0-%EC%A0%9C%ED%95%9C-exception%EC%97%90-%EB%8C%80%ED%95%B4-%EC%A7%88%EB%AC%B8%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4)
- 업로드 가능한 파일 1개의 최대 사이즈는 5MB, 하나의 요청으로 여러 개의 파일을 업로드하는 경우 총 용량은 최대 10MB까지 가능합니다. 만약 용량 제한을 풀어야 하는 경우 해당 부분 수정하면 됩니다.  
- 개발 환경에서는 `fora-dev` 버킷을, 운영 환경에서는 `fora-prd` 버킷을 사용합니다. 따라서 각 환경에 맞게 `AWS_S3_BUCKET` 환경 변수값을 각각 …
=> S3 이미지 업로드 및 삭제 구현

src/main/java/com/project/foradhd/domain/hospital/business/dto/out/HospitalOperationDetailsData.java, src/main/java/com/project/foradhd/domain/hospital/business/service/HospitalOperationService.java, src/main/java/com/project/foradhd/domain/hospital/persistence/entity/Hospital.java, src/main/java/com/project/foradhd/domain/hospital/web/controller/HospitalController.java, src/main/java/com/project/foradhd/domain/hospital/web/dto/response/HospitalDetailsResponse.java, src/main/java/com/project/foradhd/domain/hospital/web/dto/response/HospitalListBookmarkResponse.java, src/main/java/com/project/foradhd/domain/hospital/web/dto/response/HospitalListNearbyResponse.java, src/main/java/com/project/foradhd/domain/hospital/web/enums/HospitalOperationStatus.java, src/main/java/com/project/foradhd/domain/hospital/web/mapper/HospitalMapper.java, src/main/java/com/project/foradhd/global/client/GooglePlacesClient.java, src/main/java/com/project/foradhd/global/client/config/GooglePlacesClientConfig.java, src/main/java/com/project/foradhd/global/client/dto/response/GooglePlaceOpeningHoursResponse.java, src/main/java/com/project/foradhd/global/config/RedisConfig.java, src/main/java/com/project/foradhd/global/enums/RedisKeyType.java, src/main/java/com/project/foradhd/global/service/RedisService.java, src/main/resources/application.yml
- 병원 운영 상태(OPEN/CLOSED, 운영 시작/종료 시간) 조회 위한 구글 맵 API 연동
- ForA 서버에 대한 API 요청 시 내부적으로 Google Places API 호출하여 응답에 포함
- 내 주변 병원 목록 조회
- 내가 저장한 병원 목록 조회
- 병원 상세 조회
- API 요청 당 비용이 청구되므로 내부적으로 요청한 Places API 응답값 캐싱 -> 병원 운영 시작/종료 시간 기준으로 timeout 설정하여 레디스에 저장
```java
private void writeHospitalOperationDetails(HospitalOperationDetailsData hospitalOperationDetails, String placeId) {
long timeout = calculateTimeout(hospitalOperationDetails);
redisService.setValue(RedisKeyType.HOSPITAL_OPERATION_DETAILS, placeId, hospitalOperationDetails, timeout, TimeUnit.SECONDS);
}
private long calculateTimeout(HospitalOperationDetailsData hospitalOperationDetails) {
LocalDateTime now = LocalDateTime.now();
LocalDateTime operationStartTime = now.withHour(hospitalOperationDetails.getOperationStartHour()) …
```
=> 병원 운영 상태 조회를 위한 구글 맵 API 연동

src/main/java/com/project/foradhd/global/client/config/GooglePlacesClientConfig.java, src/main/resources/application-oauth2.yml, src/main/resources/application.yml
- 해당 PR 별건 없고 카카오, 네이버, 구글, 애플의 client id, client secret 키 주입 방식이 기존에는 jasypt 라이브러리로 암호화된 문자열을 코드에 삽입하는 방식이었습니다. 이 경우 해당 값들이 변경될 때마다 매번 재컴파일해야 하는 불편함이 있어 이 또한 환경 변수로 주입해주도록 설정 변경하였습니다. 
- 기존에는 jasypt 암호화 방식을 단순히 사용해보고 싶어 이렇게 구현했던 건데 생각치 못한 불편함이 있어 변경하게 되었습니다. 
- 해당 PR에서 변경되는, 추가되는 환경변수는 다음과 같습니다. ('환경변수 및 secret key 공유' 문서에서 확인해주세요)
```text
GOOGLE_API_KEY => 변수명 및 값 변경
KAKAO_CLIENT_ID
KAKAO_CLIENT_SECRET
NAVER_CLIENT_ID
NAVER_CLIENT_SECRET
GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET
=> 변수 추가
```
- 구글 Places API Client에 적용했던 관련 설정 클래스 `GooglePlacesClientConfig`가 구글 로그인 시 호출되는 `GoogleOAuth2PeopleApiClient`에도 적용되어 오류가 발생 -> `GooglePlacesClientConfig`에 포함된 `@Configuration` 어노테이션 제거하여 전역 빈으로 등록되는 `RequestInterceptor`가 특정 feign client(`@FeignClient` 어노테이션의 `configuration` 속성으로 설정한 경우에만)에만 적용되도록 설정
- …
=> 소셜 로그인 키 관리 방식 변경

src/main/java/com/project/foradhd/domain/user/business/dto/out/UserTokenData.java, src/main/java/com/project/foradhd/domain/user/business/service/UserEmailAuthService.java, src/main/java/com/project/foradhd/domain/user/business/service/UserService.java, src/main/java/com/project/foradhd/domain/user/business/service/impl/UserEmailAuthServiceImpl.java, src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java, src/main/java/com/project/foradhd/domain/user/web/controller/UserController.java, src/main/java/com/project/foradhd/domain/user/web/dto/request/EmailCheckRequest.java, src/main/java/com/project/foradhd/domain/user/web/dto/request/NicknameCheckRequest.java, src/main/java/com/project/foradhd/domain/user/web/dto/response/EmailCheckResponse.java, src/main/java/com/project/foradhd/domain/user/web/mapper/UserMapper.java, src/main/java/com/project/foradhd/global/config/SecurityConfig.java, src/test/java/com/project/foradhd/domain/user/business/service/UserEmailAuthServiceTest.java, src/test/java/com/project/foradhd/domain/user/business/service/UserServiceTest.java, src/test/java/com/project/foradhd/domain/user/web/controller/UserControllerTest.java
- 유저 이메일 중복 여부 확인 api 구현 및 테스트
- 기존 이메일 본인 인증코드 발급 및 검증 api 수정: 해당 api는 일반 회원가입 시 / 소셜 로그인 회원가입 시에만 호출 -> 전자는 `ROLE_ANONYMOUS` 권한으로, 후자는 `ROLE_GUEST` 권한으로 요청 -> 기존에는 `ROLE_GUEST` 권한 이상만 호출하도록 설정됨 -> 권한 제한 풀고 각 경우에 따라 다르게 처리하도록 수정(ex. `ROLE_GUEST` 권한인 경우 `userId`로 비교 수행)
- `UserEmailAuthServiceTest`에서 `@MockitoExtension`, `@SpringExtension`을 같이 사용할 경우, `@InjectMocks`, `@Mock`이 제대로 동작하지 않는 문제: 모킹된 `UserService`의 특정 메소드를 분명 호출하였음에도 메소드 호출 여부 검증(`then(...).should(times(1))`) 시 `mockito wanted but not invoked, Actually there were zero interactions with this mock` 에러 발생
- `@SpringExtension` 어노테이션이 잘못 동작하는 것 같은데 이유는 알아보겠음
- 해결방법: `@SpringExtension`만 사용후, `@Mock` 대신 `@MockBean` 사용하여 목빈을 `@Import(UserEmailServiceImpl.class)`로 등록된 `UserEmailServiceImpl` 빈에 주입해줌
- 기존의 닉네임 중복 여부 확인 api와 거의 유사합니다. 프론트 …
=> 유저 이메일 중복 여부 확인 api 개발

src/main/java/com/project/foradhd/domain/board/business/service/Impl/CommentServiceImpl.java, src/main/java/com/project/foradhd/domain/board/web/controller/NotificationController.java, src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java, src/main/java/com/project/foradhd/global/config/SecurityConfig.java, src/main/java/com/project/foradhd/global/config/WebConfig.java, src/main/resources/application.yml
- 애플 로그인 시 `https://appleid.apple.com` 도메인에서 직접 우리 서버 도메인으로 요청을 보내 CORS 에러 발생(naver, kakao, google 로그인과 달리 조금 다르게 구현되어 있는 듯)
- `WebConfig` 클래스 내 cors 설정에 해당 도메인 추가 (+ `SecurityConfig` 내 cors 설정 제거) 
- cors 설정을 환경변수로 주입하도록 변경 (환경변수 `CORS_ALLOWED_ORIGINS` 추가했습니다.)
- 댓글, 게시글 쪽 익명 유저에 대한 기본 프로필 이미지 경로 수정: cloud front 사용으로 S3 키로 설정하였습니다. (TODO: 디자인팀에 `default-profile.png` 이미지 파일 받은 후 S3 업로드 필요)
close #59
=> 애플 로그인 시 CORS 에러 해결

src/main/java/com/project/foradhd/domain/medicine/web/dto/MedicineDto.java, src/main/java/com/project/foradhd/domain/medicine/web/dto/response/MedicineSearchResponse.java, src/main/java/com/project/foradhd/domain/medicine/web/dto/response/MedicineSortedResponse.java, src/main/java/com/project/foradhd/domain/medicine/web/mapper/MedicineMapper.java
- 프론트쪽에서 약 게시물 목록 조회 시 응답값에 medicineId를 함께 내려달라는 요청을 받았습니다.
- 
api 요청 시 응답값은 다음과 같습니다.
- medicinemapper, medicinesearchresponse, medicinedto에 각각 medicineId 추가한 것 이외에 수정사항 없습니다. 
close #61
=> 약 게시글 조회 시 medicineId 추가

src/main/java/com/project/foradhd/domain/hospital/business/dto/out/HospitalDetailsData.java, src/main/java/com/project/foradhd/domain/hospital/business/service/HospitalService.java, src/main/java/com/project/foradhd/domain/hospital/business/service/impl/HospitalServiceImpl.java, src/main/java/com/project/foradhd/domain/hospital/web/controller/HospitalController.java, src/main/java/com/project/foradhd/domain/hospital/web/dto/request/HospitalDetailsRequest.java, src/main/java/com/project/foradhd/domain/hospital/web/dto/response/HospitalDetailsResponse.java, src/main/java/com/project/foradhd/global/util/GeoUtil.java, src/test/java/com/project/foradhd/domain/hospital/business/service/HospitalServiceTest.java, src/test/java/com/project/foradhd/domain/hospital/web/controller/HospitalControllerTest.java
- 병원 상세 조회 `GET /api/v1/hospitals/{hospitalId}` api에 요청 파라미터 `latitude`, `longitude` 및 응답 바디로 `distance`(현재 위치에서 병원까지의 거리) 값 추가
- 요청 파라미터로 전달된 위경도 좌표값과 DB에서 조회된 병원의 좌표값 사이의 거리를 구하는 유틸 클래스 `GeoUtil` 추가 구현하였습니다. 참고로 내 주변 병원 목록 조회 api에서는 자바단이 아닌 sql(`st_distance_sphere` 함수 사용)에서 현재 위치 - 병원 간의 거리를 구하고 있습니다. 
- 채은님 요청으로 api 수정하였습니다. 리뷰해주시면 바로 배포하겠습니다. 
close #67
=> 병원 상세 조회 api 수정

.gitignore, build.gradle, src/main/java/com/project/foradhd/domain/auth/filter/LoginAuthenticationFilter.java, src/main/java/com/project/foradhd/domain/auth/handler/LoginAuthenticationSuccessHandler.java, src/main/java/com/project/foradhd/global/config/SecurityConfig.java, src/main/java/com/project/foradhd/global/exception/handler/GlobalExceptionHandler.java, src/main/java/com/project/foradhd/global/filter/RequestWrapperFilter.java, src/main/java/com/project/foradhd/global/logging/logger/ApiLogger.java, src/main/resources/application.yml, src/main/resources/logback-spring.xml
Spring Logback, AOP를 이용하여 로그를 남김
- `src/main/resources/logback-spring.xml` 경로의 파일을 생성하여 실행 프로필(`local`, `dev`, `prod`) 별로 다른 로깅 방식을 취함
- `include` 태그를 통해 기본 설정값(`defaults.xml`, `console-appender.xml`)을 재사용
```xml 
<include resource="org/springframework/boot/logging/logback/defaults.xml" />
<include resource="org/springframework/boot/logging/logback/console-appender.xml" />
```
- `springPropery` 태그를 통해 logback-spring.xml 파일 내에서 사용할 변수 선언 
```xml
<springProperty name="LOG_PATH" source="log.config.path"/>
<springProperty name="LOG_FILENAME" source="log.config.filename.application"/>
<springProperty name="LOG_ERROR_FILENAME" source="log.config.filename.error"/>
<springProperty name="LOG_MAX_HISTORY" source="log.config.maxHistory"/>
<springProperty name="LOG_MAX_FILE_SIZE" …
```
=> Logback, AOP 이용한 로그 남기기

src/main/java/com/project/foradhd/domain/board/web/dto/response/PostSearchResponseDto.java
- 게시글 제목으로 검색 시 상세페이지 이동을 위해 응답 dto에 postid를 함께 포함하여 내려달라는 프론트측의 요청 반영하였습니다
- 추가된 것 postsearchreseponsedto에 id값 추가한 것 이외 수정사항 없습니다.
위와 같이 postid 함께 응답값에 포함됩니다.
close #72
=> mod: 게시글 검색 시 postid 내려주도록 수정

src/main/java/com/project/foradhd/domain/board/web/dto/response/PostSearchResponseDto.java
- 게시글 제목으로 검색 시 해당 게시물을 클릭하면 바로 이동하기 위해 postid값 추가하였습니다 (저번에 수정해서 머지한 것 같은데, 다시 develop 브랜치 풀 받아서 해보니까 안 되더라구요)
- postsearchresponsedto 이외 수정사항 없습니다.
close #75
=> mod: postsearch 응답 dto에 postid값 추가

src/main/java/com/project/foradhd/domain/board/business/service/CommentService.java, src/main/java/com/project/foradhd/domain/board/business/service/Impl/CommentServiceImpl.java, src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostLikeFilterServiceImpl.java, src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostScrapFilterServiceImpl.java, src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostServiceImpl.java, src/main/java/com/project/foradhd/domain/board/web/controller/CommentController.java, src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java, src/main/java/com/project/foradhd/domain/board/web/dto/response/CommentListResponseDto.java, src/main/java/com/project/foradhd/domain/board/web/dto/response/PostListResponseDto.java, src/main/java/com/project/foradhd/domain/board/web/mapper/CommentMapper.java, src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java, src/main/java/com/project/foradhd/domain/user/business/service/UserService.java, src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java, src/main/java/com/project/foradhd/domain/user/persistence/entity/UserBlocked.java, src/main/java/com/project/foradhd/domain/user/persistence/repository/UserBlockedRepository.java, src/main/java/com/project/foradhd/domain/user/web/controller/UserController.java, src/main/java/com/project/foradhd/domain/user/web/dto/request/UserBlockRequest.java, src/main/java/com/project/foradhd/global/exception/ErrorCode.java, src/test/java/com/project/foradhd/domain/board/business/service/CommentServiceImplTest.java, src/test/java/com/project/foradhd/domain/user/business/service/UserServiceTest.java
- 게시글, 댓글 작성자를 차단할 수 있는 기능을 구현하였습니다. 
- 차단 시 해당 작성자의 모든 게시글, 댓글 내용 가림 처림 ex. "차단한 멤버가 작성한 게시글(혹은 댓글)입니다."
- 멤버 차단 횟수 제한 없음
- 차단 해제 기능 없음
- 차단한 사용자 조회하는 기능 없음
- 각 유저별 차단 유저와의 관계를 관리하는 `UserBlocked` 엔티티 추가하였습니다. 
- 게시글, 댓글 조회 시 해당 글이 차단한 유저가 작성한 글인지는 응답 바디로 내려주는 `isBlocked`로 판단합니다. 해당 값은 `PostMapper` 또는 `CommentMapper`의 메소드 파라미터로 전달해준 `blockedUserIdList` 리스트에 작성자 ID가 포함되는지 여부로 설정됩니다. 
close #94
=> 유저 차단 기능 구현

src/main/java/com/project/foradhd/domain/board/business/service/Impl/CommentServiceImpl.java, src/main/java/com/project/foradhd/domain/board/persistence/repository/CommentRepository.java, src/main/java/com/project/foradhd/domain/board/web/controller/CommentController.java, src/main/java/com/project/foradhd/domain/board/web/mapper/CommentMapper.java, src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java
- postmapper에서 댓글과 대댓글 구분 없이 매핑하고 있어 문제가 발생하고 있음을 발견
-> postmapper에서 부모 댓글만 매핑되도록 수정하였습니다.
-
- postmapper와 commentmapper만 수정되었습니다!
close #96
=> fix: 댓글 레벨에서 대댓글 조회되는 문제 해결

src/main/java/com/project/foradhd/global/image/web/controller/FileUploadController.java, src/main/java/com/project/foradhd/global/image/web/dto/request/ImageDeleteRequest.java, src/main/java/com/project/foradhd/global/image/web/dto/request/ImageUploadRequest.java
- 이미지 파일과 DTO를 `@RequestPart`로 각각 받는 경우 application/octet-stream으로 인식
- 이미지 파일과 이미지에 대한 데이터를 DTO 하나로 받아 multipart/form-data로 인식하도록 수정
=> 이미지 업로드 요청 헤더 content-type 인식 오류 해결

src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java, src/main/java/com/project/foradhd/domain/board/web/dto/request/ReportTypeDto.java
- 클라이언트에서 보낸 신고 유형 Enum 값을 서버에서 제대로 처리 못 하는 상황. -> DTO 매핑으로 올바르게 받을 수 있도록 처리
- DTO 파일 생성했습니다!
close #111
=> fix: 게시글 신고 API 신고 유형 값 받을 때 DTO를 통한 매핑으로 받을 수 있도록 수정

src/main/java/com/project/foradhd/domain/board/business/service/dto/in/ReportPostData.java, src/main/java/com/project/foradhd/domain/board/persistence/entity/Comment.java, src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
dquote> - PostController.java: 빌더를 사용해 게시글 정보 가져오도록 해주었습니다.
- ReportPostData.java:  매핑 처리 전에 미리 필드를 맞추는것이 나을 것 같다는 생각이 들어 PostReportResponseDto과 필드를 동일하게 해주었습니다.
- Comment.java: 해당 엔티티의 정보를 가져오면서 JPA 엔티티 간의 양방향 관계가 JSON 직렬화 될 때 발생하는 문제인 무한 재귀와 Lazy Loading된 프록시 객체 직렬화 오류를  방지하기 위해 JsonIgnore어노테이션을 추가해 해당 문제들을 해결 하였습니다.
- 개발 시 오류가 났던 부분, 어떻게 해결하였는지 공유합니다. 해결하지 못했더라도 어떤 방법을 시도해 보았는지 공유하는 것도 좋습니다.
- 데이터를 가져오는 도중 양방향 관계가 JSON 직렬화 될 때 LazyLoading, 무한재귀 에러가 났었습니다. 양방향에 해당되는 필드들에 JsonIgnore어노테이션을 추가해서 직렬화 되지 않도록 해결해주었습니다
- 적절하게 작성이 되었는지 확인해주세요!
close #117
=> fix: 게시글 내용 불러올 때 null값으로 반환되는 오류 해결

src/main/java/com/project/foradhd/global/validation/validator/EmailDomainValidator.java, src/main/java/com/project/foradhd/global/validation/validator/EmailValidator.java
- 이메일 중복 체크 시 특정 도메인만 허용하는 기존 검증 방식을 모든 이메일 도메인을 허용하는 방식으로 변경
- 기존에는 `VALID_EMAIL_DOMAIN` 리스트를 유지하여 일부 이메일 도메인만 허용했으나, 이를 **이메일 형식만 검증하는 방식**으로 개선
- 정규 표현식을 사용하여 이메일 형식(xxx@yyy.zz)이 올바르면 중복 체크 가능하도록 구현
1. **MX 레코드 검증 방식 시도 → 실패**
- 이메일 도메인이 실제 존재하는지 확인하기 위해 MX 레코드 조회 방식을 검토
- Spring Boot 환경에서 서버 측에서 직접 MX 레코드 조회가 어렵고, 추가적인 네트워크 요청이 필요하여 비효율적
- 일부 학교 및 회사 이메일 (@sookmyung.ac.kr, @hy.ac.kr) 등이 **정상적으로 인식되지 않는 문제 발생**
2. 기존 도메인 제한 방식 문제
- 기존 VALID_EMAIL_DOMAIN 리스트 (naver.com, gmail.com 등) 내에서만 이메일을 허용하는 방식
- 특정 이메일 (@ac.kr, @company.com 등)이 차단되는 문제 발생
- 학교 및 기업 이메일 사용 불가
3. 최종 해결 방법: 이메일 형식 검증만 수행
✅ 모든 이메일 도메인을 허용
✅ 정규 표현식을 사용해 이메일 형식만 검증
✅ @example.com 같은 올바른 형식이면 중복 체크 가능
✅ 중복 체크의 기능만 수행하고, 회원가입 시 이메일 인증을 통해 실제 유효한 이메일인지 검증
- 이메일 인증 시 도메인 필터링 없이 모든 이메일 도메인을 허용하는 방식으로 변경됨
- MX 레코드 검증을 고려했으나 …
=> fix: 이메일 허용 도메인 수정

src/main/java/com/project/foradhd/domain/medicine/business/service/impl/MedicineReviewServiceImpl.java, src/main/java/com/project/foradhd/domain/medicine/persistence/entity/MedicineCoMedication.java, src/main/java/com/project/foradhd/domain/medicine/persistence/entity/MedicineReview.java, src/main/java/com/project/foradhd/domain/medicine/web/mapper/MedicineReviewMapper.java, src/main/java/com/project/foradhd/global/validation/validator/EmailDomainValidator.java, src/main/java/com/project/foradhd/global/validation/validator/EmailValidator.java
**🚀 MedicineCoMedication 엔티티 추가 및 기존 로직 개선**
- MedicineReview와 Medicine 간 다대다(@ManyToMany) 관계를 다루기 위해 중간 테이블을 별도의 엔티티(`MedicineCoMedication`)로 분리
- 기존에는 medicine_co_medications 테이블을 Hibernate에서 자동 생성했지만, 명시적인 엔티티로 관리하도록 변경
- 새로운 엔티티의 테이블명을 `medicine_co_medication`(s빠짐!!) 으로 지정하여 기존 테이블과 충돌을 방지
- 
**🔄 MedicineReview와 MedicineCoMedication 관계 설정**
- 기존에는 MedicineReview가 medicine_id를 리스트로 직접 관리했지만 **중간 엔티티**(`MedicineCoMedication`)를 통해 연관관계를 관리
- `MedicineReview` **저장 이후** `MedicineCoMedication` **엔티티를 생성**하여 연관 데이터를 추가
❌ **오류:** `Field 'review_id' doesn't have a default value`
- 원인: 
`review_id`가 NULL인 상태에서 `medicine_co_medications`에 데이터가 삽입됨
- 해결 방법:
`MedicineReview` 엔티티를 먼저 저장한 후 `MedicineCoMedication`을 추가하도록 코드 수정
Lambda 표현식에서 `medicineReview`가 effectively final 상태로 유지되도록 변경
❌ **오류**: …
=> fix: 약 리뷰 작성 시 500 에러 수정

src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java, src/main/java/com/project/foradhd/domain/board/web/dto/response/PostRankingResponseDto.java, src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java
- 전체 게시글 isBlocked null 반환 에러 해결
- 게시글 & 카테고리별 랭킹순 조회 isBlocked 필드 반환 하도록 수정
- 해당 사항 없음
- 오타와 같은 부분이 있는지 확인 부탁 드립니다.
close #123
=> 게시글 & 카테고리별 랭킹순 조회 isBlocked 필드 미반환 및 전체 게시글 조회 api isBlocked 필드 null 반환 

src/main/java/com/project/foradhd/domain/board/persistence/entity/CommentLikeFilter.java
- commentlikefilter 엔티티 내 comment와의 다대일 관계에서 cascade 설정 오류 수정
- 개발 시 오류가 났던 부분, 어떻게 해결하였는지 공유합니다. 해결하지 못했더라도 어떤 방법을 시도해 보았는지 공유하는 것도 좋습니다.
- 리뷰어가 중점적으로 보아야 할 부분, 전반적인 컨텍스트를 공유합니다. 이해를 돕기 위해 이미지 등을 활용해도 좋습니다.
close #(이슈번호)
=> fix: 댓글 좋아요 두 번 누를 경우 댓글 삭제되는 에러 수정

src/main/java/com/project/foradhd/domain/board/persistence/repository/CommentLikeFilterRepository.java, src/main/java/com/project/foradhd/domain/board/web/mapper/PostMapper.java
**## 💻 구현 내용** 
**🔹 댓글 매핑 방식 변경 (`@AfterMapping` 적용)**
**✅ 기존 방식**
- 기존에는 `mapCommentList`를 `@Mapping `단계에서 직접 호출하여 댓글 리스트를 매핑함
**🔧 해결 방법**
- `@Mapping`에서 `comments` 필드를 `ignore = true`로 변경
- `@AfterMapping`을 활용하여, 매핑이 완료된 후 댓글 리스트를 추가하는 방식으로 변경
- CommentMapper, UserService, CommentService, blockedUserIdList, loggedInUserId 등을 @Context로 전달하여,
의존성을 주입받아 `mapCommentList`를 실행하도록 변경
**## 🛠️ 개발 오류 사항**
**❌ 오류: CommentMapper.INSTANCE 접근 문제 및 매핑 오류**
**✅ 원인**
- 기존 방식에서는 `@Mapping `단계에서 `mapCommentList`를 호출했기 때문에, MapStruct가 의존성을 자동으로 주입하지 못함
- `CommentMapper.INSTANCE`를 직접 참조하는 방식이었으므로, MapStruct에서 이를 해석하지 못하고 오류 발생
- 또한 `isUserLikedComment`, `isCommentAuthor` 등의 사용자 기반 정보는 @Mapping 단계에서 접근 불가능
**🔧 해결 방법**
@Mapping에서 comments 필드를 ignore = true로 변경
@AfterMapping에서 mapCommentList를 호출하여 댓글 리스트를 설정
✅ …
=> fix: 게시글 댓글 조회시 500에러 수정

src/main/java/com/project/foradhd/domain/board/business/service/Impl/CommentServiceImpl.java, src/main/java/com/project/foradhd/domain/board/persistence/repository/CommentRepository.java
- 댓글 목록 조회 시 대댓글이 최상단 댓글 리스트에 중복 노출되는 현상 제거
- 기존에는 `postId`로 조회할 때 대댓글도 함께 불러와 `children`에도, 최상단에도 중복으로 표시됨
- `parentComment is null `조건을 걸어 **최상위 댓글만 조회하도록 변경**
- 댓글 + 대댓글 + 유저 + 유저 프로필을 `@EntityGraph`로 `Fetch Join` 처리
- 댓글 수가 많지 않아도 `N+1 쿼리 문제`로 인해 느리던 성능 이슈 해결
- 🔥 조회 시간이 **14초 → 4초** 이내로 단축 🔥
- 기존 댓글 조회 API에서 대댓글이 `parentComment != null`인데도 리스트 최상단에 노출되는 이슈가 발생함
- `comment.getChildComments()`에서 `children`으로도 포함되고 `findByPostId()`로 전체 댓글을 가져오며 대댓글도 함께 포함됨 → 중복 표시됨
- 또한 댓글 수는 적은데 **N+1 문제로 인한 응답 지연**이 발생
- userProfile, isLiked, isCommentAuthor 등을 댓글마다 개별 쿼리로 조회하고 있었음
**🥟 해결 방법**
- `findByPostIdAndParentCommentIsNull(postId)`로 최상위 댓글만 조회하도록 변경
- `@EntityGraph`를 활용해 댓글 + 대댓글 + 유저 + 유저 프로필까지 `Fetch Join `처리
- 기존 댓글 조회 API 응답 구조는 그대로 유지하면서 중복 제거 및 성능 개선에 집중했습니다.
- 성능 테스트 결과 동일 데이터 기준에서 14초 …
=> fix: 대댓글 작성 시 댓글 중복 업로드 수정

src/main/java/com/project/foradhd/domain/user/business/service/impl/UserServiceImpl.java, src/main/java/com/project/foradhd/global/exception/ErrorCode.java
**비밀번호 변경 시 기존 비밀번호와 동일한 경우 예외 처리 추가**
- 사용자가 기존 비밀번호와 동일한 비밀번호로 변경을 시도할 경우, `BusinessException`을 발생시켜 변경을 막도록 로직을 추가했습니다.
- 사용자 실수로 인해 동일한 비밀번호를 재사용하는 것을 방지하고, 보안성 향상을 위해 필요한 제약 조건입니다.
**상세 로직**
- `UserServiceImpl`의 `updatePassword` 메서드 내에서 기존 비밀번호와 새 비밀번호를 비교
- 동일할 경우 `PASSWORD_SAME_AS_PREVIOUS` 에러 코드와 함께 예외 발생
- 비밀번호 변경 시 기존 비밀번호와 동일한지 확인하는 로직이 `UserServiceImpl` 내부에서 수행되도록 수정했습니다.
- 보안 정책 및 사용자 경험 관점에서 이 예외 처리 로직이 적절한지 + 위치나 방식이 개선될 여지가 있는지 함께 확인 부탁드립니다.
- 기존 비밀번호와 같은 비밀번호를 입력했을 경우 or 기존 사용 중인 비밀번호를 잘못 입력했을 경우 에러 처리가 제대로 수행되는지 확인 부탁드립니다.
close #149
=> feat: 비밀번호 변경 시 기존 비밀번호랑 동일할 경우 에러 처리

src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostServiceImpl.java, src/main/java/com/project/foradhd/domain/board/business/service/PostService.java, src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
**카테고리별 게시글 최신순 정렬 기능 개선**
- 기존에는 `/api/v1/posts/category` 요청 시 `SortOption` 파라미터가 무시되어 항상 기본 정렬(`createdAt DESC`)로 작동했습니다.
- 이를 해결하기 위해 `PostController`, `PostService`, `PostServiceImpl`에 정렬 옵션(`SortOption`)을 반영한 로직을 추가하였습니다.
- 정렬 기준에는 최신순(`NEWEST_FIRST`), 오래된순(OLDEST_FIRST), 조회수순(`MOST_VIEWED`), 좋아요순(`MOST_LIKED`), 댓글순(`MOST_COMMENTED`) 등을 지원합니다.
- 문제: 
프론트에서 `sortOption=NEWEST_FIRST`로 요청을 보내도 정렬이 적용되지 않음.
- 원인 분석: 
`PostServiceImpl`의 `listByCategory` 메서드에 `SortOption` 파라미터가 없었고, 내부에서도 정렬 처리가 누락되어 있었음.
- 해결 방법:
`listByCategory` 메서드에 `SortOption`을 추가하고, 이를 기반으로 `Pageable`에 정렬 기준을 적용하는 `applySorting` 메서드를 작성하여 동적으로 정렬 가능하도록 개선함
- `/api/v1/posts/category` API에서 `sortOption` 쿼리 파라미터를 기반으로 동작이 잘 적용되었는지 확인 부탁드립니다.
- 서비스 계층에서 동작하는 정렬 기준이 실제로 Query에 잘 반영되었는지, 그리고 `SortOption`이 적절히 적용되는지 봐주시면 …
=> fix: 카테고리 별 글 조회 시 정렬옵션 수정

src/main/java/com/project/foradhd/domain/user/persistence/entity/UserProfile.java
- 회원 탈퇴 요청시 500에러 수정
- 회원 탈퇴시 UserProfile에 nickname이 공백 상태로 저장 되도록 하는 로직이었습니다
- nickname에는 중복 제약이 걸려있어 여러 유저가 탈퇴를 할 경우 중복 에러 때문에 탈퇴가 되지 않음을 확인 했습니다.
- nickname에 탈퇴한 유저가 명시 되도록 수정해주었습니다.
- 더 좋은 방법이 있다면 말씀해주세요
close #154
=> 회원탈퇴 500에러 수정

src/main/java/com/project/foradhd/domain/board/business/service/Impl/CommentServiceImpl.java, src/main/java/com/project/foradhd/domain/board/persistence/entity/Comment.java, src/main/java/com/project/foradhd/domain/board/persistence/repository/CommentRepository.java, src/main/java/com/project/foradhd/domain/board/web/dto/response/CommentListResponseDto.java, src/main/java/com/project/foradhd/domain/board/web/mapper/CommentMapper.java
**1. Soft Delete 기반 댓글 삭제 처리 로직 개선**
- 기존에는 댓글 삭제 시 DB에서 완전 삭제되어 댓글 목록 조회 시 아예 보이지 않음
- 이를 개선하여 대댓글이 존재하는 원댓글의 경우 실제 삭제하지 않고 `"삭제된 댓글입니다." `형태로 남기도록 변경
- 댓글 엔티티에 `deleted`, `deletedMessage` 필드 추가
- 매퍼에서 `isDeleted` 상태일 경우:
- `nickname` → (삭제)
- `content` → "삭제된 댓글입니다."
- `profileImage` → 기본 이미지로 대체
- 삭제된 댓글도 조회 리스트에 포함되도록 `CommentRepository`의 `JPQL` 수정
- 댓글 `soft delete` 처리 후 삭제된 댓글이 댓글 목록 API에서 아예 보이지 않는 현상 발생
- 원인: `findTopLevelCommentsWithChildren` JPQL 쿼리에 `isDeleted = false` 조건이 포함되어 있었음
- 해결: 해당 조건 제거하여 `soft deleted` 댓글도 포함되도록 수정
- 삭제된 댓글이 어떻게 응답에 포함되는지 확인해주세요. (글 별 댓글 조회 `api {{host}}/api/v1/comments/posts/{{postId}}?sortOption=NEWEST_FIRST&page=0&size=10` 와, 개별 댓글 조회 api `{{host}}/api/v1/comments/{{commentId}}`)
- 삭제된 댓글은 `nickname`: (삭제), `content`: 삭제된 댓글입니다. 로 표현됩니다.
- 대댓글이 있는 …
=> mod: 댓글 soft delete 되도록 수정

src/main/java/com/project/foradhd/domain/board/persistence/entity/Comment.java, src/main/java/com/project/foradhd/domain/board/persistence/entity/Post.java
**🔧 default 값 문제 해결**
- 초기 댓글 생성 시 `deleted` 필드에 `default` 값이 없어 다음과 같은 에러가 발생했습니다.
- `Field 'deleted' doesn't have a default value`
- 이를 해결하기 위해 `@Column(nullable = false)`에` @ColumnDefault("false")` 어노테이션을 추가하고,
- `@Builder.Default private boolean deleted = false;`로 명시적인 초기값을 설정했습니다.
- soft delete 로직을 위해 `boolean` 필드(`deleted`)에 대한 default 값 처리에 주의했습니다.
- 혹시 해당 방식 외에 더 안정적이거나 추천하는 방식이 있다면 공유 부탁드립니다!
close #158
=> fix: 댓글 작성 시 deleted 필드 기본값 설정

src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostServiceImpl.java
- `카테고리별 글 정렬 API(listByCategory)`에서 해당 카테고리에 등록된 글이 없는 경우에도 `BusinessException(NOT_FOUND_POST)`을 발생시키지 않고, 빈 리스트를 반환하도록 수정하였습니다.
- 기존에는 글이 하나도 없는 경우 예외가 발생했음
- 변경 후에는` Page<Post>` 객체를 그대로 반환하므로, 프론트에서` .isEmpty()` 여부로 처리할 수 있습니다.
- 문제: 카테고리에 글이 존재하지 않으면 `BusinessException(NOT_FOUND_POST)` 예외가 발생하여 404 오류로 응답되던 문제.
- 해결: if (posts.isEmpty()) 조건을 제거하여 빈 리스트를 200 OK와 함께 반환하도록 변경.
- PostServiceImpl의 listByCategory 메서드 내 조건문 제거로 처리했습니다.
close #160
=> mod: 카테고리 별 글 조회 시 글 없을 경우 빈 리스트 반환

src/main/java/com/project/foradhd/global/validation/validator/PasswordValidator.java
**비밀번호 정규식 수정**
- 기존 정규식은 제한된 일부 특수문자만 허용 (`[@#$%^&+=!.]`)
- 모든 특수문자 허용을 위해 정규식 수정
`// 변경 전
private static final String DEFAULT_PASSWORD_REGEX = "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[@#$%^&+=!])(?=\\S+$).{8,}$";
// 변경 후
private static final String DEFAULT_PASSWORD_REGEX = "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9])(?=\\S+$).{8,}$";
`
- 설명:
- 숫자(0-9) 1개 이상
- 영문자(a-zA-Z) 1개 이상
- 특수문자([^a-zA-Z0-9]) 1개 이상
- 공백 없이 총 8자 이상
- 문제점: 기존 정규식에서는 .(dot) 등 일부 특수문자가 허용되지 않아 사용자가 예상한 입력값이 실패하는 문제가 있었음
- 해결 방법: 특수문자 범위를 [`^a-zA-Z0-9`]로 확장하여 대부분의 특수문자 허용
- 변경된 정규식이 보안 요건(숫자 + 영문 + 특수문자 + 공백 제외 + 8자 이상)을 모두 충족하는지 확인 부탁드립니다
- 혹시 더 강력한 정책(예: 대소문자 구분 포함 등)이 필요하다면 코멘트 주세요
close #168
=> fix: 비밀번호 특수문자 수정

src/main/java/com/project/foradhd/domain/medicine/business/service/impl/MedicineReviewServiceImpl.java, src/main/java/com/project/foradhd/domain/medicine/persistence/repository/MedicineReviewLikeRepository.java, src/main/java/com/project/foradhd/domain/medicine/persistence/repository/MedicineReviewRepository.java, src/main/java/com/project/foradhd/domain/medicine/web/controller/MedicineReviewController.java, src/main/java/com/project/foradhd/domain/medicine/web/dto/response/MedicineReviewResponse.java, src/main/java/com/project/foradhd/domain/medicine/web/mapper/MedicineReviewMapper.java
- 약 리뷰 조회 시 로그인한 유저가 해당 리뷰의 작성자인지 판별하여 isAuthor 필드로 내려주도록 구현하였습니다.
- 로그인한 유저의 식별자인 `userId`를 `@AuthUserId`를 통해 컨트롤러에서 추출하고, 매퍼에서 리뷰 작성자의 ID와 비교하여 `isAuthor` 여부를 판단합니다.
###**MedicineReviewResponse DTO**
- boolean `isAuthor` 필드 추가
- Jackson 직렬화 시 "isAuthor"로 명확히 내려주기 위해 `@JsonProperty("isAuthor")` 어노테이션 사용
###**Mapper 변경 사항**
- `toResponseDto` 메서드에 `@Context String currentUserId` 파라미터 추가
- `@AfterMapping` 내에서 r`eview.getUser().getId().equals(currentUserId)`로 작성자 여부 판단
###**Controller 변경 사항**
- 모든 리뷰 조회 API(`getReviews`, `getReviewsByMedicineId`, `getUserReviews`, `createReview`, `updateReview`)에서 `userId`를 매퍼에 넘기도록 수정
`isAuthor`로 정의된 필드가 JSON 응답에서 "`author`"로 내려오는 문제 발생
→ 원인: Lombok이 `isAuthor` 필드에 대해 `isIsAuthor()`라는 getter를 자동 생성하여 Jackson이 필드를 "`author`"로 직렬화함
→ 해결: …
=> mod: 약 리뷰 조회 시 작성자 확인 필드 추가

build.gradle, src/main/resources/application.yml
- application.yml: prometheus, health, info endpoint 노출
- application.yml: 메트릭 export 활성화 & application 태그로 서비스명 지정
- build.gradle: Prometheus 연동을 위해 micrometer registry 및 actuator 의존성 추가
- build.gradle: 메트릭 수집 및 노출을 위한 기반 구성
close #177
=> feat: prometheus 설정

build.gradle, src/main/java/com/project/foradhd/domain/user/persistence/entity/User.java
- 기존에 User 엔티티가 `UserPrivacy`와의 연관 관계를 명시적으로 가지고 있지 않아, EntityGraph나 Fetch Join 시 오류가 발생함
- 이를 해결하기 위해 `User` 엔티티에 `UserPrivacy`와의 1:1 연관 관계를 명시적으로 추가
- @EntityGraph 사용 시 "Unable to locate Attribute with the given name [userPrivacy] on this ManagedType" 오류 발생
- 원인: User 엔티티에 userPrivacy 필드가 존재하지 않았기 때문
- 시도한 해결 방법:
처음엔 Fetch Join 쿼리 방식으로 우회 시도 → 동작은 가능하나 코드 일관성이 떨어짐
- 최종 해결:
User 엔티티에 userPrivacy 필드 추가하고 연관 관계 매핑함으로써 EntityGraph 정상 작동 확인
- User ↔ UserPrivacy의 연관 관계 매핑 방식이 적절한지
- 기존 EntityGraph를 사용하는 쿼리에서 정상적으로 작동하는지 (N+1 문제 해결 여부 포함)
- cascade, fetch 설정이 서비스 흐름에 적절한지
- 연관된 Entity 변경 사항이므로 추후 DB schema에도 영향이 없는지 한 번 확인 부탁드립니다.
close #181
=> bugfix: 약 별 리뷰 조회 시 500에러 해결
